name: SuperVanish-V2
version: 2.0.0
api: [3.0.0-ALPHA11]
author: VMPE Development Team
main: Vanish\Main

commands:
    sv: 
        permission: supervanish.spectate
        description: "Vanishes the player who uses the command!"
        usage: "/sv on/off"
