name: Vanish
version: 1.0
api: [3.0.0-ALPHA10]
author: iCirgio
main: Vanish\Main

commands:
    vanish: 
        permission: vanish.command
        description: "Vanishes the player who uses the command!"
        usage: "/vanish on/off"
